# Generated by Django 5.1.4 on 2024-12-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, default='', max_length=3000, null=True)),
                ('invoice_number', models.IntegerField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Client Name')),
                ('line_one', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Line 1')),
                ('line_one_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_one_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit price (D)')),
                ('line_one_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('line_two', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Line 2')),
                ('line_two_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quanity')),
                ('line_two_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit price (D)')),
                ('line_two_total_price', models.IntegerField(blank=True, default=True, null=True, verbose_name='Line Total (D)')),
                ('line_three', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Line 3')),
                ('line_three_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qunatity')),
                ('line_three_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit price (D)')),
                ('line_three_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('line_four', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Line 4')),
                ('line_four_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qunatity')),
                ('line_four_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)')),
                ('line_four_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('line_five', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Line 5')),
                ('line_five_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qunatity')),
                ('line_five_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)')),
                ('line_five_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('line_six', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Line 6')),
                ('line_six_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qunatity')),
                ('line_six_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)')),
                ('line_six_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('line_seven', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Line 7')),
                ('line_seven_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qunatity')),
                ('line_seven_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)')),
                ('line_seven_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('line_eight', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Line 8')),
                ('line_eight_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qunatity')),
                ('line_eight_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)')),
                ('line_eight_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('line_nine', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Line 9')),
                ('line_nine_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qunatity')),
                ('line_nine_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)')),
                ('line_nine_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('phone_number', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('balance', models.IntegerField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('invoice_type', models.CharField(blank=True, choices=[('Invoice', 'Invoice'), ('Receipt', 'Receipt'), ('Proforma Invoice', 'Proforma Invoice')], default='', max_length=50, null=True)),
            ],
        ),
    ]
