# Generated by Django 5.1.4 on 2024-12-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('Receipt', 'Receipt'), ('Proforma Invoice', 'Proforma Invoice'), ('Invoice', 'Invoice')], default='', max_length=50, null=True),
        ),
    ]
